<a href="https://colab.research.google.com/github/endnef2/big_leader/blob/main/DL/Pytorch_Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Pytroch Autograd

In [ ]:
import torch

In [ ]:
torch.__version__

'2.0.1+cu118'

In [ ]:
x = torch.randn(3)
y = x+2

In [ ]:
x

tensor([-1.4668, -0.7241, -1.2085])

In [ ]:
y

tensor([0.5332, 1.2759, 0.7915])

In [ ]:
z = y*y*3

In [ ]:
# z의 평균값
z.mean()

tensor(2.5387)

In [ ]:
z.mean().item()

2.5386996269226074

In [ ]:
a = torch.rand(2,2,requires_grad=True)
a

tensor([[0.7529, 0.8410],
        [0.5952, 0.1657]], requires_grad=True)

In [ ]:
a.requires_grad

True

In [ ]:
# requires_gard 빼고 tensor valure 값만
a.detach()

tensor([[0.7529, 0.8410],
        [0.5952, 0.1657]])

In [ ]:
# torch.no_gard()
with torch.no_grad():
  print((x**2).requires_grad)

False


In [ ]:
# torch.no_gard()
with torch.no_grad():
  print((x**2))

tensor([2.1515, 0.5243, 1.4606])


In [ ]:
weight = torch.ones(4, requires_grad=True)

# 학습시킬 때 파이토치는 for 문 사용
for epoch in range(5):
  model_out = (weight*3).sum()
  model_out.backward()

  print(weight.grad)

  with torch.no_grad():
    weight-=0.1*weight.grad # weight 조정 weight = weight-0.1(learning rate)*weight.grad

  weight.grad.zero_()

print(weight)
print(model_out)

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([-0.5000, -0.5000, -0.5000, -0.5000], requires_grad=True)
tensor(-2.4000, grad_fn=<SumBackward0>)


## 2. Backpropagation

In [ ]:
x = torch.tensor(1.0)
y = torch.tensor(2.0)

In [ ]:
w = torch.tensor(1.0, requires_grad=True)

In [ ]:
y_predict = w * x

In [ ]:
loss = (y-y_predict)**2

In [ ]:
print(loss)

tensor(1., grad_fn=<PowBackward0>)


In [ ]:
loss.backward()
w.grad

tensor(-2.)

In [ ]:
with torch.no_grad():
  w -= 0.01 *w.grad

# 값을 0으로 바꿔라
w.grad.zero_()

tensor(0.)

## 3. Gradient Descent: Manually

In [ ]:
import numpy as np

X = np.array([1,2,3,4], dtype=np.float32)
Y = np.array([2,4,6,8], dtype=np.float32)

w = 0.0 # 실수로 넣어주기

In [ ]:
def forward(x):
  return w*x

In [ ]:
def loss(y, y_pred):
  return ((y_pred-y)**2).mean()

In [ ]:
def gradient(x, y, y_pred):
  return np.dot(2*x, y_pred-y).mean()
print(forward(5))

0.0


In [ ]:
# training
learning_rate = 0.01
n_iters = 20

for epoch in range(n_iters):
  # forward pass
  y_pred = forward(X)

  # loss
  l = loss(Y, y_pred)

  # gradients 계산
  dw = gradient(X, Y, y_pred) # input, output, 예측값

  # update weight
  w -= learning_rate * dw

  if epoch%2==0:
    print(f'epoch {epoch+1}: w = {w:.3f}, loss={l:.4f}')
print(f'predict after training: f(5)={forward(5):.3f}')

epoch 1: w = 1.200, loss=30.0000
epoch 3: w = 1.872, loss=0.7680
epoch 5: w = 1.980, loss=0.0197
epoch 7: w = 1.997, loss=0.0005
epoch 9: w = 1.999, loss=0.0000
epoch 11: w = 2.000, loss=0.0000
epoch 13: w = 2.000, loss=0.0000
epoch 15: w = 2.000, loss=0.0000
epoch 17: w = 2.000, loss=0.0000
epoch 19: w = 2.000, loss=0.0000
predict after training: f(5)=10.000


## 4. Gradient Descent : Autograd

In [ ]:
import torch

X = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
Y = torch.tensor([2, 4, 6, 8], dtype=torch.float32)

w = torch.tensor(0.0, dtype=torch.float32, requires_grad=True)

In [ ]:
def forward(x):
  return w*x

def loss(y, y_pred):
  return ((y_pred-y)**2).mean()

In [ ]:
# torch training
learning_rate = 0.01
n_iters = 100

for epoch in range(n_iters):
  # forward predict
  y_pred = forward(X)

  # loss
  l = loss(Y, y_pred)

  # backward pass
  l.backward()

  # update weights
  # w.data = w.data - learning_rate*w.grad
  with torch.no_grad():
    w -= learning_rate*w.grad

  # update 후에 w를 zero화 시킨다.
  w.grad.zero_()

  if epoch % 10 == 0:
    print(f'epoch:{epoch+1}:w={w.item():.3f},loss={l.item():4f}')
print(f'Prediction after training: f(5)={forward(5).item():.3f}')

epoch:1:w=0.300,loss=30.000000
epoch:11:w=1.665,loss=1.162786
epoch:21:w=1.934,loss=0.045069
epoch:31:w=1.987,loss=0.001747
epoch:41:w=1.997,loss=0.000068
epoch:51:w=1.999,loss=0.000003
epoch:61:w=2.000,loss=0.000000
epoch:71:w=2.000,loss=0.000000
epoch:81:w=2.000,loss=0.000000
epoch:91:w=2.000,loss=0.000000
Prediction after training: f(5)=10.000


## 5. Loss Function & Optimizer

In [ ]:
import torch
import torch.nn as nn

X = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
Y = torch.tensor([2, 4, 6, 8], dtype=torch.float32)

w = torch.tensor(0.0, dtype=torch.float32, requires_grad=True)

In [ ]:
def forward(x):
  return w*x

In [ ]:
# hyper parameter
learning_rate = 0.01
n_iters = 100

In [ ]:
# loss function and optimizer
loss = nn.MSELoss()
optimizer = torch.optim.SGD([w], lr=learning_rate)

In [ ]:
for epoch in range(n_iters):
  # forward predict
  y_pred = forward(X)

  # loss
  l = loss(Y, y_pred)

  # backward pass
  l.backward()

  # update weights
  optimizer.step()

  # update 후에 w를 zero화 시킨다.
  optimizer.zero_grad()

  if epoch % 10 == 0:
    print('epoch', epoch+1, ':w=', w, 'loss=', l)

print(f'Prediction after training: f(5)={forward(5).item():.3f}')

epoch 1 :w= tensor(0.3000, requires_grad=True) loss= tensor(30., grad_fn=<MseLossBackward0>)
epoch 11 :w= tensor(1.6653, requires_grad=True) loss= tensor(1.1628, grad_fn=<MseLossBackward0>)
epoch 21 :w= tensor(1.9341, requires_grad=True) loss= tensor(0.0451, grad_fn=<MseLossBackward0>)
epoch 31 :w= tensor(1.9870, requires_grad=True) loss= tensor(0.0017, grad_fn=<MseLossBackward0>)
epoch 41 :w= tensor(1.9974, requires_grad=True) loss= tensor(6.7705e-05, grad_fn=<MseLossBackward0>)
epoch 51 :w= tensor(1.9995, requires_grad=True) loss= tensor(2.6244e-06, grad_fn=<MseLossBackward0>)
epoch 61 :w= tensor(1.9999, requires_grad=True) loss= tensor(1.0176e-07, grad_fn=<MseLossBackward0>)
epoch 71 :w= tensor(2.0000, requires_grad=True) loss= tensor(3.9742e-09, grad_fn=<MseLossBackward0>)
epoch 81 :w= tensor(2.0000, requires_grad=True) loss= tensor(1.4670e-10, grad_fn=<MseLossBackward0>)
epoch 91 :w= tensor(2.0000, requires_grad=True) loss= tensor(5.0768e-12, grad_fn=<MseLossBackward0>)
Prediction

## 6. Advanced Training

In [ ]:
# 1차원이 아닌 2차원으로 넣어야 error가 나지 않는다.
import torch
import torch.nn as nn

X = torch.tensor([[1], [2], [3], [4]], dtype=torch.float32)
Y = torch.tensor([[2], [4], [6], [8]], dtype=torch.float32)

n_samples, n_features = X.shape

In [ ]:
X_test = torch.tensor([5], dtype=torch.float32)
X_test

tensor([5.])

In [ ]:
input_size = n_features
output_size = Y.shape[1]

In [ ]:
# model build
model = nn.Linear(input_size, output_size)

In [ ]:
class LinearRegression(nn.Module):
  def __init__(self, input_dim, output_dim):
      super(LinearRegression, self).__init__()
      # define Layers
      self.lin = nn.Linear(input_dim, output_dim)

  def forward(self, x):
      return self.lin(x)

In [ ]:
model = LinearRegression(input_size, output_size)

In [ ]:
learning_rate = 0.01
n_iters=100

# loss function and optimizer
loss = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

In [ ]:
for epoch in range(n_iters):
  # forward predict
  y_pred = model(X)

  # loss
  l = loss(Y, y_pred)

  # backward pass
  l.backward()

  # update weights
  optimizer.step()

  # update 후에 w를 zero화 시킨다.
  optimizer.zero_grad()

  if epoch % 10 == 0:
    w, b = model.parameters()
    print('epoch', epoch+1, ':w=', w[0].item(), 'loss=', l)

print(f'Prediction after training: f(5)={model(X_test).item():.3f}')

epoch 1 :w= -0.20477956533432007 loss= tensor(62.6068, grad_fn=<MseLossBackward0>)
epoch 11 :w= 1.6085729598999023 loss= tensor(1.6225, grad_fn=<MseLossBackward0>)
epoch 21 :w= 1.9013354778289795 loss= tensor(0.0446, grad_fn=<MseLossBackward0>)
epoch 31 :w= 1.9494807720184326 loss= tensor(0.0036, grad_fn=<MseLossBackward0>)
epoch 41 :w= 1.9582483768463135 loss= tensor(0.0024, grad_fn=<MseLossBackward0>)
epoch 51 :w= 1.9606518745422363 loss= tensor(0.0022, grad_fn=<MseLossBackward0>)
epoch 61 :w= 1.9620023965835571 loss= tensor(0.0021, grad_fn=<MseLossBackward0>)
epoch 71 :w= 1.9631550312042236 loss= tensor(0.0020, grad_fn=<MseLossBackward0>)
epoch 81 :w= 1.9642481803894043 loss= tensor(0.0019, grad_fn=<MseLossBackward0>)
epoch 91 :w= 1.965305209159851 loss= tensor(0.0017, grad_fn=<MseLossBackward0>)
Prediction after training: f(5)=9.930
